import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import LandingPageLayout from "@/components/layouts/LandingPageLayout";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
	team,
	analytics,
}: Readonly<{
	children: React.ReactNode;
	analytics: React.ReactNode;
	team: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body className={inter.className}>
				<LandingPageLayout>
					{children} {team} {analytics}
				</LandingPageLayout>
			</body>
		</html>
	);
}
